'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ELECTION_CAP_VOTE
    Public Property ID_VOTE As Integer
    Public Property ID_ELECTEUR As Integer
    Public Property ID_CANDIDAT As Integer
    Public Property ID_CORPS_GROUPE As Integer
    Public Property DATE_VOTE As Nullable(Of Date)
    Public Property IP_ENSEIGNANT As String
    Public Property PAYS As String

End Class
